//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dynamic_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub source_id: i32,
    pub dynamic_id: String,
    pub upper_id: i64,
    pub upper_name: String,
    pub pub_time: DateTime,
    pub content: String,
    pub raw_json: String,
    pub image_count: u32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dynamic_post_image::Entity")]
    DynamicPostImage,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SourceId",
        to = "super::submission::Column::Id"
    )]
    Submission,
}

impl Related<super::dynamic_post_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicPostImage.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
