//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dynamic_post_image")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dynamic_post_id: i32,
    pub url: String,
    pub width: u32,
    pub height: u32,
    pub local_path: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dynamic_post::Entity",
        from = "Column::DynamicPostId",
        to = "super::dynamic_post::Column::Id"
    )]
    DynamicPost,
}

impl Related<super::dynamic_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DynamicPost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
