//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod collection;
pub mod config;
pub mod dynamic_post;
pub mod dynamic_post_image;
pub mod favorite;
pub mod page;
pub mod submission;
pub mod video;
pub mod watch_later;
